# Generated by Django 4.0.4 on 2022-04-18 18:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0003_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, default='static/photos/business.jpg', max_length=255, verbose_name='image'),
        ),
    ]
