# Generated by Django 4.0.4 on 2022-04-18 21:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_alter_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
